all:
  hosts:
    node1:
      ansible_host: 192.168.11.130
      ip: 192.168.11.130
      access_ip: 192.168.11.130
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
            #    calico_rr:
            #      hosts: {}
