all:
  hosts:
    node1:
      ansible_host: 10.252.97.29
      ip: 10.252.97.29
      access_ip: 10.252.97.29
    node2:
      ansible_host: 10.252.97.28
      ip: 10.252.97.28
      access_ip: 10.252.97.28
    node3:
      ansible_host: 10.252.97.30
      ip: 10.252.97.30
      access_ip: 10.252.97.30
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
